development:
  adapter: postgresql
  encoding: unicode
  database: ccheese_development
  pool: 5
  host: localhost
  username: budisugianto
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ccheese_test
  pool: 5
  host: localhost
  username: budisugianto
  password: